name: Build Main CWS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  CI-Main-CWS:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Build
      uses: ./.github/actions/action.yml
      with:
        branchName: master
        dbTarget: rc
        msBuildConfig: Release
        targetOption: 'Compile,PrecompileWeb,RunTests'
        cleanCheckout: true