name: Build Main Warehouse

on:
  workflow_dispatch: #Allows manual trigger

jobs:
  Build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2    
    - name: Build
      uses: ./.github/templates/build/warehouse
      with:
        branchName: master
        cleanCheckout: true