name: Build Main Integrations

on:
  push:
    branches:
      - main
  workflow_dispatch: #Allows manual trigger

jobs:
  Build-Main-Integrations:
    uses: dlarang/it-bamboo-pipeline/.github/workflows/template-build-integrations.yml@main
    with:
      branchName: master
      cleanCheckout: true