name: Build RC Interview

on:
  push:
    branches:
      - main
  workflow_dispatch: #Allows manual trigger

jobs:
  Build-RC-Interview:
    uses: dlarang/it-bamboo-pipeline/.github/workflows/template-build-interview.yml@main
    with:
      branchName: releaseCandidate
      cleanCheckout: true