name: Build Main CWS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  CI-Main-CWS:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: List files
      run: ls -R
    
    - name: Print working directory
      run: pwd

    - name: List files
      run: ls 
    
    - name: List files
      run: dir .github/build
    
    - name: Build
      uses: ./.github/templates/build/cws
      with:
        branchName: master
        dbTarget: rc
        msBuildConfig: Release
        targetOption: 'Compile,PrecompileWeb,RunTests'
        cleanCheckout: true
