name: Build RC CWS

on:
  workflow_dispatch: #Allows manual trigger

jobs:
  Build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      uses: ./.github/templates/build/cws
      with:
        branchName: releaseCandidate
        dbTarget: rc
        msBuildConfig: Release
        targetOption: 'Compile,PrecompileWeb,RunTests'
        cleanCheckout: true