name: Build RC PR

on:
  push:
    branches:
      - main
  workflow_dispatch: #Allows manual trigger

jobs:
  Build-RC-PR:
    uses: dlarang/it-bamboo-pipeline/.github/workflows/template-build-pr.yml@main
    with:
      branchName: releaseCandidate
      cleanCheckout: true