name: Build Main CWS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  CI-Main-CWS:
    runs-on: windows-latest
    steps:    
    - name: Build
      uses: ./.github/templates/build/cws
      with:
        branchName: master
        dbTarget: rc
        msBuildConfig: Release
        targetOption: 'Compile,PrecompileWeb,RunTests'
        cleanCheckout: true
