name: Build Main CWS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  Checkout:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Upload code as artifact
      uses: actions/upload-artifact@v2
      with:
        name: workspace
        path: ./
  Build:
    needs: Checkout
    runs-on: windows-latest
    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: workspace
      - name: Build
        uses: ./.github/templates/build/cws
        with:
          branchName: master
          dbTarget: rc
          msBuildConfig: Release
          targetOption: 'Compile,PrecompileWeb,RunTests'
          cleanCheckout: true
