name: Build Main PR

on:
  push:
    branches:
      - main
  workflow_dispatch: #Allows manual trigger

jobs:
  Build-Main-PR:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2    
    - name: Build
      uses: ./.github/templates/build/pr
      with:
        branchName: master
        cleanCheckout: true