name: Build RC CWS

on:
  push:
    branches:
      - main
  workflow_dispatch: #Allows manual trigger

jobs:
  Build-RC-CWS:
    uses: dlarang/it-bamboo-pipeline/.github/workflows/template-build-cws.yml@main
    with:
      branchName: releaseCandidate
      dbTarget: rc
      msBuildConfig: Release
      targetOption: 'Compile,PrecompileWeb,RunTests'
      cleanCheckout: true