name: Build Main CWS

on:
  push:
    branches:
      - main
  workflow_dispatch: #Allows manual trigger

jobs:
  CI-Main-CWS:
    runs-on: windows-latest
    steps:
    - name: Build
      uses: dlarang/it-bamboo-pipeline/.github/reusable-steps/build-cws.yml@main
      with:
        branchName: master
        dbTarget: rc
        msBuildConfig: Release
        targetOption: 'Compile,PrecompileWeb,RunTests'
        cleanCheckout: true