name: Build Main CWS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  Checkout:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
  Build:
    needs: Checkout
    runs-on: windows-latest
    steps:
      - name: Build
        uses: ./.github/templates/build/cws
        with:
          branchName: master
          dbTarget: rc
          msBuildConfig: Release
          targetOption: 'Compile,PrecompileWeb,RunTests'
          cleanCheckout: true
