name: CI Main Interview

on:
  push:
    branches:
      - main
  workflow_dispatch: #Allows manual trigger

jobs:
  CI-Main-Interview:
    uses: dlarang/it-bamboo-pipeline/.github/workflows/template-build-interview.yml@main
    with:
      branchName: master
      cleanCheckout: true