name: CI Main ImportApi

on:
  push:
    branches:
      - main
  workflow_dispatch: #Allows manual trigger

jobs:
  CI-Main-ImportApi:
    uses: dlarang/it-bamboo-pipeline/.github/workflows/template-build-importapi.yml@main
    with:
      branchName: master
      cleanCheckout: true