name: Deploy US QA Regression

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  Deploy:
    uses: ./.github/workflows/deployment.yml
    with:
      environmentProperties: |
        {
          "versionToUse": "D:\\AzureDevOps-Store\\dynamic\\azcandidate.txt",
          "extractFolder": "QARegCodeExtract",
          "sourceZIPPath": "D:\\Code\\AzCandidate"
        }