name: Dynamic Steps from JSON Input

on:
  workflow_dispatch:
    inputs:
      batches:
        description: 'Batches JSON Input'
        required: true
        default: |
          [
            {
              "number": 1,
              "webServers": [
                {
                  "fqdn": "prodweb201.fra.beeline.com",
                  "name": "prodweb201",
                  "iisRestart": true,
                  "diskDrive": "D",
                  "folder": "CWS",
                  "sourcePath": "\\Source\\Prod\\",
                  "destinationPaths": ["\\Source\\Prod\\"],
                  "servicesToCheck": ["IISADMIN", "WAS", "W3SVC"]
                },
                {
                  "fqdn": "prodweb203.fra.beeline.com",
                  "name": "prodweb203",
                  "iisRestart": true,
                  "diskDrive": "D",
                  "folder": "CWS",
                  "sourcePath": "\\Source\\Prod\\",
                  "destinationPaths": ["\\Source\\Prod\\"],
                  "servicesToCheck": ["IISADMIN", "WAS", "W3SVC"]
                }
              ]
            }
          ]
        type: string

jobs:
  parse-json:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Parse JSON and Generate Matrix
      id: set-matrix
      run: |
        echo "Parsing JSON input..."
        echo '${{ github.event.inputs.batches }}' > batches.json
        webServers=$(jq -c '[.[] | .webServers[]]' batches.json)
        echo "::set-output name=matrix::$webServers"

  dynamic-steps:
    needs: parse-json
    runs-on: ubuntu-latest
    strategy:
      matrix:
        webServer: ${{ fromJson(needs.parse-json.outputs.matrix) }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Process web server
      shell: pwsh
      run: |
        Write-Host "Processing web server ${{ matrix.webServer.fqdn }}"
        Write-Host "Name: ${{ matrix.webServer.name }}"
        Write-Host "IIS Restart: ${{ matrix.webServer.iisRestart }}"
        Write-Host "Disk Drive: ${{ matrix.webServer.diskDrive }}"
        Write-Host "Folder: ${{ matrix.webServer.folder }}"
        Write-Host "Source Path: ${{ matrix.webServer.sourcePath }}"
        Write-Host "Destination Paths: ${{ matrix.webServer.destinationPaths }}"
        Write-Host "Services to Check: ${{ matrix.webServer.servicesToCheck }}"