name: 'My Composite Action'
description: 'An example composite action that performs different steps based on a security scan flag'
inputs:
  isForSecurityScan:
    description: 'Flag to indicate if this is for security scanning.'
    type: boolean
    required: true
    default: false

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      if: ${{ !inputs.isForSecurityScan }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Run Security Scan
      if: ${{ inputs.isForSecurityScan }}
      run: |
        echo "Running security scan..."

    - name: Run Regular Tests
      if: ${{ !inputs.isForSecurityScan }}
      run: |
        echo "Running regular tests..."
