name: Dynamic Job Example

on:
  workflow_dispatch:
    inputs:
      upgrade_index:
        description: 'Upgrade Index'
        default: '1'

jobs:
  notify:
    name: Notify ${{ github.event.inputs.upgrade_index }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run upgrade-${{ github.event.inputs.upgrade_index }}
      run: |
        echo "Running upgrade-${{ github.event.inputs.upgrade_index }}"