name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      isForSecurityScan:
        description: 'Flag to indicate if this is for security scanning.'
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Security Scan Flag
        run: echo "isForSecurityScan is set to ${{ github.event.inputs.isForSecurityScan }}"

      - name: Run Security Scan
        if: ${{ github.event.inputs.isForSecurityScan }}
        run: echo "Running security scan..."

      - name: Run Regular Tasks
        if: ${{ !github.event.inputs.isForSecurityScan }}
        run: echo "Running regular tasks..."
