name: Build Interview

on:
  workflow_call:
    inputs:
      branchName:
        description: 'Branch Name'
        required: true
        default: 'master'
        type: string
      cleanCheckout:
        description: 'cleanCheckout'
        required: true
        default: true
        type: boolean

jobs:
  Build-Artifact:
    runs-on: windows-latest
    steps:
    - name: Checkout Interview
      shell: pwsh
      run: |
        Write-Output "Checkout to Interview complete"
    - name: Build
      shell: pwsh
      run: |
        Write-Output "Build complete"
    - name: Archived File
      shell: pwsh
      run: |
        Write-Output "Archived File complete"