name: Test Variables

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  Test-Config-Variables:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install yq
      run: |
        sudo apt-get update
        sudo apt-get install -y yq
    - name: Read config variables
      shell: pwsh
      run: |
        $config = yq e '.variables' config-variables.yml
        $version_dll = yq e '.variables.VERSION_DLL' config-variables.yml
        $service_account = yq e '.variables.SERVICE_ACCOUNT' config-variables.yml
        $internaltools_username = yq e '.variables.INTERNALTOOLS_USERNAME' config-variables.yml

        Write-Host "Version DLL: $version_dll"
        Write-Host "Service Account: $service_account"
        Write-Host "InternalTools Username: $internaltools_username"